version: "3.7"
services:
  notary:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    ports:
      - "7886:7886"
    volumes:
      - "./nodes/notary/:/opt/nuts/"
    # optional for console logging
    command: "-jar /opt/nuts/corda.jar --network-root-truststore-password=changeit --log-to-console --initial-registration"
    deploy:
      restart_policy:
        condition: none

  manson:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    ports:
      - "2222:2222"
      - "17886:7886"
    volumes:
      - "./nodes/manson/:/opt/nuts/"
    command: "-jar /opt/nuts/corda.jar --network-root-truststore-password=changeit --log-to-console --initial-registration"
    deploy:
      restart_policy:
        condition: none
networks:
  nuts:
    name: nuts
