version: "3.7"
services:
  notary:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    ports:
      - "7886:24960"
    volumes:
      - "./nodes/notary/:/opt/nuts/"
    # optional for console logging
    command: "-jar /opt/nuts/corda.jar --network-root-truststore-password=changeit --log-to-console"
    restart: "always"
  host:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    ports:
      - "2222:2222"
      - "17886:24964"
    volumes:
      - "./nodes/host/:/opt/nuts/"
    command: "-jar /opt/nuts/corda.jar --network-root-truststore-password=changeit --log-to-console"
    restart: "always"
  bridge:
    image: nutsfoundation/nuts-consent-bridge:latest-dev
    environment:
      SPRING_SERVER_ADDRESS: manson-bridge
    networks:
      - nuts
    ports:
      - "18080:8080"
    volumes:
      - "./nodes/host/application.properties:/opt/nuts/application.properties"
    restart: "always"
  nuts-service-space:
    image: nutsfoundation/nuts-service-space:latest
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    networks:
      nuts:
        aliases:
          - registry
    ports:
      - "11323:1323"
    volumes:
      - "./nodes/host/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./nodes/host/keys:/opt/nuts/keys"
networks:
  nuts:
    name: nuts
