version: "3.7"
services:
  corda:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    ports:
      - "2222:2222"
      - "7886:7886"
    volumes:
      - "./node/:/opt/nuts/"
    command: "-jar /opt/nuts/corda.jar --network-root-truststore-password=changeit --log-to-console"
    deploy:
      restart_policy:
        condition: all
        delay: 15s
        max_attempts: 3
        window: 120s
  bridge:
    image: nutsfoundation/nuts-consent-bridge:latest-dev
    environment:
      SPRING_SERVER_ADDRESS: bridge
    networks:
      - nuts
    ports:
      - "8080:8080"
    volumes:
      - "./node/application.properties:/opt/nuts/application.properties"
    deploy:
      restart_policy:
        condition: all
        delay: 15s
        max_attempts: 3
        window: 120s
  nuts-service-space:
    image: nutsfoundation/nuts-service-space:latest
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    networks:
      nuts:
        aliases:
          - registry
    ports:
      - "11323:1323"
    volumes:
      - "./node/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./node/keys:/opt/nuts/keys"
networks:
  nuts:
    name: nuts
