version: "3.7"
services:
  corda:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    ports:
      - "22222:2222"
      - "27886:17495"
    volumes:
      - "./node/:/opt/nuts/"
    command: "-jar /opt/nuts/corda.jar --network-root-truststore-password=changeit --log-to-console"
    restart: "always"
  bridge:
    image: nutsfoundation/nuts-consent-bridge:latest-dev
    environment:
      SPRING_SERVER_ADDRESS: bridge
    networks:
      - nuts
    ports:
      - "28080:8080"
    volumes:
      - "./node/application.properties:/opt/nuts/application.properties"
    restart: "always"
  nuts-service-space:
    image: nutsfoundation/nuts-service-space:latest
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    networks:
      nuts:
        aliases:
          - registry
    ports:
      - "21323:1323"
    volumes:
      - "./node/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./node/keys:/opt/nuts/keys"
    restart: "always"
networks:
  nuts:
    name: nutsp
